import type { Metadata } from "next";
import { Inter, Exo, Raleway, Arimo } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

const inter = Inter({ subsets: ["latin"] });

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you want to use
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Wordman",
  description: "Generated by Wordman 2024",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${exo.className} ${raleway.className} ${arimo.className} vsc-initialized`}
        >
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
